#include "nextviper/native_compiler.hpp"
#include "nextviper/interpreter.hpp"
#include "nextviper/compiler.hpp"
#include "nextviper/vm.hpp"
#include <sstream>
#include <fstream>
#include <cstdlib>
#include <chrono>
#include <cstdio>
#include <iostream>
#include <array>

namespace nextviper {

NativeCompiler::NativeCompiler(DiagnosticEngine& diag) : diag_(diag) {}

std::string NativeCompiler::find_c_compiler() const {
    // Check standard C compilers in PATH
    if (std::system("which gcc > /dev/null 2>&1") == 0) return "gcc";
    if (std::system("which clang > /dev/null 2>&1") == 0) return "clang";
    if (std::system("which g++ > /dev/null 2>&1") == 0) return "g++";
    if (std::system("which cc > /dev/null 2>&1") == 0) return "cc";
    return "cc";
}

std::string NativeCompiler::emit_native_source(const IRModule& module) const {
    std::ostringstream ss;
    ss << "/* Generated by NextViper High-Performance Native Compiler */\n";
    ss << "#include <stdio.h>\n";
    ss << "#include <stdlib.h>\n";
    ss << "#include <stdint.h>\n";
    ss << "#include <stdbool.h>\n";
    ss << "#include <math.h>\n\n";

    // Standard NextViper Native Runtime helpers
    ss << "static inline void nv_print_i64(int64_t v) { printf(\"%ld\\n\", (long)v); }\n";
    ss << "static inline void nv_print_f64(double v) { printf(\"%f\\n\", v); }\n";
    ss << "static inline void nv_print_str(const char* s) { printf(\"%s\\n\", s ? s : \"null\"); }\n";
    ss << "static inline void nv_print_bool(bool b) { printf(\"%s\\n\", b ? \"true\" : \"false\"); }\n\n";

    // Forward declarations
    for (const auto& fn : module.functions) {
        if (fn->name == "main") continue;
        ss << "int64_t nv_fn_" << fn->name << "(";
        for (size_t i = 0; i < fn->params.size(); ++i) {
            if (i > 0) ss << ", ";
            ss << "int64_t " << fn->params[i].first;
        }
        ss << ");\n";
    }
    ss << "\n";

    // Function definitions
    for (const auto& fn : module.functions) {
        if (fn->name == "main") {
            ss << "int main(int argc, char** argv) {\n";
            ss << "  (void)argc; (void)argv;\n";
        } else {
            ss << "int64_t nv_fn_" << fn->name << "(";
            for (size_t i = 0; i < fn->params.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << "int64_t " << fn->params[i].first;
            }
            ss << ") {\n";
        }

        // Emit blocks
        for (const auto& bb : fn->blocks) {
            ss << " " << bb->label << ":\n";

            for (const auto& inst : bb->instructions) {
                switch (inst.opcode) {
                    case IROpcode::CONST_INT:
                        ss << "  int64_t r" << inst.dest_reg << " = " << inst.args[0].int_val << "LL;\n";
                        break;
                    case IROpcode::CONST_FLOAT:
                        ss << "  double r" << inst.dest_reg << " = " << inst.args[0].float_val << ";\n";
                        break;
                    case IROpcode::CONST_BOOL:
                        ss << "  bool r" << inst.dest_reg << " = " << (inst.args[0].bool_val ? "true" : "false") << ";\n";
                        break;
                    case IROpcode::CONST_STRING:
                        ss << "  const char* r" << inst.dest_reg << " = \"" << inst.args[0].str_val << "\";\n";
                        break;
                    case IROpcode::CONST_NIL:
                        ss << "  void* r" << inst.dest_reg << " = NULL;\n";
                        break;
                    case IROpcode::ALLOCA:
                        ss << "  int64_t r" << inst.dest_reg << " = 0; /* var " << inst.args[0].str_val << " */\n";
                        break;
                    case IROpcode::LOAD:
                        ss << "  int64_t r" << inst.dest_reg << " = r" << inst.args[0].reg_id << ";\n";
                        break;
                    case IROpcode::STORE:
                        if (inst.args[1].kind == OperandKind::REGISTER) {
                            ss << "  r" << inst.args[0].reg_id << " = r" << inst.args[1].reg_id << ";\n";
                        } else if (inst.args[1].kind == OperandKind::CONSTANT_INT) {
                            ss << "  r" << inst.args[0].reg_id << " = " << inst.args[1].int_val << "LL;\n";
                        } else if (inst.args[1].kind == OperandKind::SYMBOL) {
                            ss << "  r" << inst.args[0].reg_id << " = " << inst.args[1].str_val << ";\n";
                        }
                        break;
                    case IROpcode::ADD:
                        ss << "  int64_t r" << inst.dest_reg << " = r" << inst.args[0].reg_id << " + r" << inst.args[1].reg_id << ";\n";
                        break;
                    case IROpcode::SUB:
                        ss << "  int64_t r" << inst.dest_reg << " = r" << inst.args[0].reg_id << " - r" << inst.args[1].reg_id << ";\n";
                        break;
                    case IROpcode::MUL:
                        ss << "  int64_t r" << inst.dest_reg << " = r" << inst.args[0].reg_id << " * r" << inst.args[1].reg_id << ";\n";
                        break;
                    case IROpcode::DIV:
                        ss << "  int64_t r" << inst.dest_reg << " = (r" << inst.args[1].reg_id << " != 0) ? (r" << inst.args[0].reg_id << " / r" << inst.args[1].reg_id << ") : 0;\n";
                        break;
                    case IROpcode::MOD:
                        ss << "  int64_t r" << inst.dest_reg << " = (r" << inst.args[1].reg_id << " != 0) ? (r" << inst.args[0].reg_id << " % r" << inst.args[1].reg_id << ") : 0;\n";
                        break;
                    case IROpcode::NEG:
                        ss << "  int64_t r" << inst.dest_reg << " = -r" << inst.args[0].reg_id << ";\n";
                        break;
                    case IROpcode::NOT:
                        ss << "  bool r" << inst.dest_reg << " = !r" << inst.args[0].reg_id << ";\n";
                        break;
                    case IROpcode::EQ:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " == r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::NE:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " != r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::LT:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " < r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::LE:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " <= r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::GT:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " > r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::GE:
                        ss << "  bool r" << inst.dest_reg << " = (r" << inst.args[0].reg_id << " >= r" << inst.args[1].reg_id << ");\n";
                        break;
                    case IROpcode::JMP:
                        ss << "  goto " << inst.args[0].str_val << ";\n";
                        break;
                    case IROpcode::JMP_IF_TRUE:
                        ss << "  if (r" << inst.args[0].reg_id << ") goto " << inst.args[1].str_val << ";\n";
                        break;
                    case IROpcode::JMP_IF_FALSE:
                        ss << "  if (!r" << inst.args[0].reg_id << ") goto " << inst.args[1].str_val << ";\n";
                        break;
                    case IROpcode::CALL:
                        ss << "  int64_t r" << inst.dest_reg << " = nv_fn_" << inst.args[0].str_val << "(";
                        for (size_t i = 1; i < inst.args.size(); ++i) {
                            if (i > 1) ss << ", ";
                            if (inst.args[i].kind == OperandKind::REGISTER) {
                                ss << "r" << inst.args[i].reg_id;
                            } else if (inst.args[i].kind == OperandKind::CONSTANT_INT) {
                                ss << inst.args[i].int_val << "LL";
                            }
                        }
                        ss << ");\n";
                        break;
                    case IROpcode::PRINT:
                        for (const auto& arg : inst.args) {
                            if (arg.kind == OperandKind::REGISTER) {
                                ss << "  nv_print_i64(r" << arg.reg_id << ");\n";
                            } else if (arg.kind == OperandKind::CONSTANT_INT) {
                                ss << "  nv_print_i64(" << arg.int_val << "LL);\n";
                            } else if (arg.kind == OperandKind::CONSTANT_STRING) {
                                ss << "  nv_print_str(\"" << arg.str_val << "\");\n";
                            }
                        }
                        break;
                    case IROpcode::RET:
                        if (!inst.args.empty()) {
                            if (inst.args[0].kind == OperandKind::REGISTER) {
                                ss << "  return r" << inst.args[0].reg_id << ";\n";
                            } else if (inst.args[0].kind == OperandKind::CONSTANT_INT) {
                                ss << "  return " << inst.args[0].int_val << "LL;\n";
                            }
                        } else {
                            ss << "  return 0;\n";
                        }
                        break;
                    default:
                        break;
                }
            }
        }
        ss << "  return 0;\n";
        ss << "}\n\n";
    }

    return ss.str();
}

bool NativeCompiler::compile_to_binary(const IRModule& module, const std::string& output_binary_path) {
    std::string c_src = emit_native_source(module);
    std::string temp_c = output_binary_path + ".tmp.c";

    std::ofstream out(temp_c);
    if (!out.is_open()) return false;
    out << c_src;
    out.close();

    std::string compiler = find_c_compiler();
    std::string cmd = compiler + " -O3 " + temp_c + " -o " + output_binary_path + " -lm 2>&1";

    int ret = std::system(cmd.c_str());
    std::remove(temp_c.c_str());
    return ret == 0;
}

bool NativeCompiler::compile_program(const Program& program, const std::string& output_binary_path, bool optimize) {
    IRGenerator gen(diag_);
    auto ir_module = gen.generate(program);
    if (!ir_module || diag_.has_errors()) return false;

    if (optimize) {
        IROptimizer opt;
        opt.optimize(*ir_module);
    }

    return compile_to_binary(*ir_module, output_binary_path);
}

std::pair<int, std::string> NativeCompiler::compile_and_run(const Program& program, bool optimize) {
    std::string temp_bin = "/tmp/nextviper_native_exec_" + std::to_string(std::chrono::system_clock::now().time_since_epoch().count());
    if (!compile_program(program, temp_bin, optimize)) {
        return {-1, "Compilation failed"};
    }

    // Execute compiled machine binary and capture output
    std::string output;
    std::array<char, 256> buffer;
    FILE* pipe = popen(temp_bin.c_str(), "r");
    if (!pipe) {
        std::remove(temp_bin.c_str());
        return {-1, "Failed to run compiled binary"};
    }

    while (fgets(buffer.data(), buffer.size(), pipe) != nullptr) {
        output += buffer.data();
    }

    int exit_code = pclose(pipe);
    std::remove(temp_bin.c_str());
    return {exit_code, output};
}

BenchmarkResult NativeCompiler::benchmark(const Program& program, const std::string& source_code, int iterations) {
    BenchmarkResult res;
    res.iterations = iterations;

    // 1. Benchmark AST Interpreter
    {
        auto start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i < iterations; ++i) {
            SourceManager sm;
            DiagnosticEngine diag(sm, false);
            Interpreter interp(diag);
            interp.execute(program);
        }
        auto end = std::chrono::high_resolution_clock::now();
        res.interpreter_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;
    }

    // 2. Benchmark Bytecode VM
    {
        SourceManager sm;
        DiagnosticEngine diag(sm, false);
        BytecodeCompiler compiler(diag);
        auto fn = compiler.compile(program);

        if (fn) {
            auto start = std::chrono::high_resolution_clock::now();
            for (int i = 0; i < iterations; ++i) {
                VM vm(diag);
                vm.run(fn);
            }
            auto end = std::chrono::high_resolution_clock::now();
            res.vm_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;
        }
    }

    // 3. Benchmark Native Compiled Machine Code
    {
        std::string temp_bin = "/tmp/nextviper_bench_bin";
        if (compile_program(program, temp_bin, true)) {
            auto start = std::chrono::high_resolution_clock::now();
            for (int i = 0; i < iterations; ++i) {
                int r = std::system((temp_bin + " > /dev/null 2>&1").c_str());
                (void)r;
            }
            auto end = std::chrono::high_resolution_clock::now();
            res.native_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;
            std::remove(temp_bin.c_str());
        }
    }

    if (res.native_ms > 0.0) {
        res.native_speedup_vs_interpreter = res.interpreter_ms / res.native_ms;
        res.native_speedup_vs_vm = res.vm_ms / res.native_ms;
    }

    return res;
}

} // namespace nextviper
